### ISSUE TITLE
[Question] Windows phone support

### ISSUE THREAD

**Issue by radiovisual** [SamVerschueren/mobicon#1]
Is there any planned support for windows phones?

The challenge for this would be that some of the Windows phone icons are not square:

| Icon name | 240% | 140% | 100% |
| --- | --- | --- | --- |
| Square 71×71 Logo | 170×170 | 99×99 | 71×71 |
| Square 150×150 Logo | 360×360 | 210×210 | 150×150 |
| Wide 310×150 Logo | **744×360** | **434×210** | **310×150** |
| Square 44×44 Logo | 106×106 | 62×62 | 44×44 |
| Store Logo | 120×120 | 70×70 | 50×50 |
| Badge Logo | 58×58 | 33×33 | 24×24 |
| Splash Screen | **1152×1920** | **672×1120** | **480×800** |

I know the the splash screen image doesn't matter, since you have [mobisplash](https://github.com/SamVerschueren/mobisplash) for that, but non-square icons requires a different approach then you are currently taking in this module. 

**Note:** The chart above is just a sample, and isn't 100% complete.

**Comment by SamVerschueren** [comment]
Should definitely be implemented. I was thinking of allowing to specify a dimension either as an array `[310, 150]` or as string `310x150`. Happy to receive other opinions or feedback!

**Comment by radiovisual** [comment]
That's exactly the implementation I had in mind, since most icons are square, and it keeps the platform.json file clean by not adding an extra "height" property just for those rare icons that aren't square.

**Comment by SamVerschueren** [comment]
Willing to do a PR :)? Guess I like the string representation more because it's more expressive.

**Comment by radiovisual** [comment]
I would be happy to provide a PR! :smile:

**Comment by radiovisual** [comment]
I started working on this, but then I got a phone call from "the boss", which has shifted my entire schedule for the next little while. What I managed to accomplish before things changed could provide someone with a headstart if someone manages to get to this before me.

**First headstart advantage:** I wrote a small module to extract size objects from string sizes: 
`"100x200"` → `{width: 100, height: 200}` called [size-from-string](https://github.com/radiovisual/size-from-string).

**Second headstart advantage:** Below is all the data you need in the `platforms.json` file to create icons for the Windows Phone 8.1 platform:

<pre>
"windows8": {
    "icons": [
      {
        "file": "Square71×71Logo.scale-100.png",
        "dimension": "71"
      },
      {
        "file": "Square71×71Logo.scale-140.png",
        "dimension": "99"
      },
      {
        "file": "Square71×71Logo.scale-240.png",
        "dimension": "170"
      },
      {
        "file": "Square150×150Logo.scale-100.png",
        "dimension": "150"
      },
      {
        "file": "Square150×150Logo.scale-140.png",
        "dimension": "210"
      },
      {
        "file": "Square150×150Logo.scale-240.png",
        "dimension": "360"
      },
      {
        "file": "Wide310×150Logo.scale-100.png",
        "dimension": "310x150"
      },
      {
        "file": "Wide310×150Logo.scale-140.png",
        "dimension": "434x210"
      },
      {
        "file": "Wide310×150Logo.scale-240.png",
        "dimension": "744x360"
      },
      {
        "file": "Square44×44Logo.scale-100.png",
        "dimension": "44"
      },
      {
        "file": "Square44×44Logo.scale-140.png",
        "dimension": "62"
      },
      {
        "file": "Square44×44Logo.scale-240.png",
        "dimension": "106"
      },
      {
        "file": "StoreLogo50x50.scale-100.png",
        "dimension": "50"
      },
      {
        "file": "StoreLogo50x50.scale-140.png",
        "dimension": "70"
      },
      {
        "file": "StoreLogo50x50.scale-240.png",
        "dimension": "120"
      },
      {
        "file": "BadgeLogo24x24.scale-100.png",
        "dimension": "24"
      },
      {
        "file": "BadgeLogo24x24.scale-140.png",
        "dimension": "33"
      },
      {
        "file": "BadgeLogo24x24.scale-240.png",
        "dimension": "58"
      }
    ]
  }
</pre>

If nobody gets to this before I have a chance to work on it again, I will be happy to pick up where I left off.

**Comment by SamVerschueren** [comment]
@radiovisual Where do you get the list of the icon sizes? Found this article: https://www.creativefreedom.co.uk/icon-designers-blog/windows-phone-8-1-app-icon-size-guide/

**Comment by radiovisual** [comment]
@SamVerschueren , I got my tile sizes directly from the Microsoft Icon Templates (https://developer.microsoft.com/en-us/windows/design/assets), and then I compared these sizes to other Windows Phone Icon Generators online. 

It is notoriously difficult to get these size sources directly from Microsoft resources, because they failed at publishing the sizes (thinking that everyone was going to use the Icon Generator built into Visual Studio and live happily ever after). 

It is also easy to get tripped up because it's not easy to determine the "mobile-only" icons from the Windows UWP Icon Sets, since Microsoft just wants you to render your icons as if you are going to launch your app to every single Windows Platform on the planet, simultaneously.

If I made a mistake, I can take a closer look a little later on.

**Comment by SamVerschueren** [comment]
Thanks for the explanation. I was just wondering because really, the MS documentation sucks. Are these sizes still the same for windows 10 then? And what about windows phone/windows mobile?

**Comment by radiovisual** [comment]
The MS documentation is **H.O.R.R.I.B.L.E**. The sizes for Windows 10 are different, and they come with options.

Here is a list of all the Windows 10 icons, with an explanation at the bottom:

<pre>
LockScreenLogo.scale-100.png
LockScreenLogo.scale-125.png
LockScreenLogo.scale-150.png
LockScreenLogo.scale-200.png
LockScreenLogo.scale-400.png
SplashScreen.scale-100.png
SplashScreen.scale-125.png
SplashScreen.scale-150.png
SplashScreen.scale-200.png
SplashScreen.scale-400.png
Square150x150Logo.scale-100.png
Square150x150Logo.scale-125.png
Square150x150Logo.scale-150.png
Square150x150Logo.scale-200.png
Square150x150Logo.scale-400.png
Square310x310Logo.scale-100.png
Square310x310Logo.scale-125.png
Square310x310Logo.scale-150.png
Square310x310Logo.scale-200.png
Square310x310Logo.scale-400.png
Square44x44Logo.scale-100.png
Square44x44Logo.scale-125.png
Square44x44Logo.scale-150.png
Square44x44Logo.scale-200.png
Square44x44Logo.scale-400.png
Square44x44Logo.targetsize-16.png
Square44x44Logo.targetsize-16_altform-unplated.png
Square44x44Logo.targetsize-20.png
Square44x44Logo.targetsize-20_altform-unplated.png
Square44x44Logo.targetsize-24.png
Square44x44Logo.targetsize-24_altform-unplated.png
Square44x44Logo.targetsize-256.png
Square44x44Logo.targetsize-256_altform-unplated.png
Square44x44Logo.targetsize-30.png
Square44x44Logo.targetsize-30_altform-unplated.png
Square44x44Logo.targetsize-32.png
Square44x44Logo.targetsize-32_altform-unplated.png
Square44x44Logo.targetsize-36.png
Square44x44Logo.targetsize-36_altform-unplated.png
Square44x44Logo.targetsize-40.png
Square44x44Logo.targetsize-40_altform-unplated.png
Square44x44Logo.targetsize-48.png
Square44x44Logo.targetsize-48_altform-unplated.png
Square44x44Logo.targetsize-60.png
Square44x44Logo.targetsize-60_altform-unplated.png
Square44x44Logo.targetsize-64.png
Square44x44Logo.targetsize-64_altform-unplated.png
Square44x44Logo.targetsize-72.png
Square44x44Logo.targetsize-72_altform-unplated.png
Square44x44Logo.targetsize-80.png
Square44x44Logo.targetsize-80_altform-unplated.png
Square44x44Logo.targetsize-96.png
Square44x44Logo.targetsize-96_altform-unplated.png
Square71x71Logo.scale-100.png
Square71x71Logo.scale-125.png
Square71x71Logo.scale-150.png
Square71x71Logo.scale-200.png
Square71x71Logo.scale-400.png
StoreLogo.scale-100.png
StoreLogo.scale-125.png
StoreLogo.scale-150.png
StoreLogo.scale-200.png
StoreLogo.scale-400.png
Wide310x150Logo.scale-100.png
Wide310x150Logo.scale-125.png
Wide310x150Logo.scale-150.png
Wide310x150Logo.scale-200.png
Wide310x150Logo.scale-400.png
</pre>

If you notice the icons that have the `_altform-unplated.png` suffix, that is a naming convention that lets you tell the runtime to render the icon without a background, so the Square icons can either be "plated" (default) or "unplated", there is no reason to include both in your app. You can't render Windows 10 icon files with a colored background, so mobicon would need to know when it is rendering Windows icons, and always set the background to `transparent`. Colored backgrounds for icons are set inside the Project Manifest (via Visual Studio), so the icon file itself must be transparent to facilitate this setting.

You can find info about the Windows 10 Tile sizes here: https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-app-assets

**Comment by SamVerschueren** [comment]
Closing this as it feels a little irrelevant nowadays. Feel free to open a new issue regarding Windows Phone support or add a PR.
