### ISSUE TITLE
ios Support missing a file size

### ISSUE THREAD

**Issue by mavezum** [SamVerschueren/mobicon#8]
XCode currently requires an icon-20 size, for iPad Notifications. This file size is missing from your exported list.

Awesome tool by the way!

**Comment by SamVerschueren** [comment]
Hi @mavezum, I can't seem to find it in the [official list](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/#spotlight-and-settings-icons).

![image](https://user-images.githubusercontent.com/1913805/64451723-1468a000-d0e5-11e9-980b-b206cdce4d98.png)

But looking in XCode itself, there is a `icon-20` missing like you say. I've add it to [`ios-icon-list`](https://github.com/SamVerschueren/ios-icon-list) which is used under the hood so this should be fixed 👌.
